name: gitub pages

on:
  push:
    branches:
      - master
    paths:
      - lib/**
      - example/**
      - vue.config.js

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: install
        run: yarn

      - name: build
        run:  yarn build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
